# .gitlab-ci.yml

# Definiert das Docker-Image, das für alle Jobs in dieser Pipeline verwendet wird.
image: maven:3.9.6-eclipse-temurin-21-alpine

# Definiert die verschiedenen Phasen (Stages) unserer Pipeline.
stages:
  - build
  - test
  - report
  - deploy_report # Für GitLab Pages Hosting des Allure Reports

# Definition von Umgebungsvariablen, die in den Jobs verwendet werden können.
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showLogFileName=false"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  # Erhöhe das Service-Timeout für den Runner.
  GITLAB_ANY_SERVICE_TIMEOUT: 120 # Timeout in Sekunden (2 Minuten)

# Definiert einen Cache für Maven-Abhängigkeiten.
cache:
  paths:
    - .m2/repository

build_job:
  stage: build # Gehört zur 'build'-Phase
  script: # Die Befehle, die ausgeführt werden sollen
    - echo "Building the project..."
    - mvn $MAVEN_CLI_OPTS compile
  artifacts: # Was dieser Job als "Ergebnis" für nachfolgende Jobs speichert
    paths:
      - target/classes
      - target/test-classes
    expire_in: 1 hour

test_job:
  stage: test # Gehört zur 'test'-Phase
  services: # Definiert den Selenium Chrome Standalone Service, der parallel gestartet wird
    - selenium/standalone-chrome:4.20.0 # Spezifische und hoffentlich stabile Version
  variables:
    # Der Hostname unter dem der Selenium-Service im Docker-Netzwerk des Runners erreichbar ist.
    SELENIUM_HOST: "selenium__standalone-chrome" 
    SELENIUM_PORT: "4444" # Standard-Port für Selenium Grid/Standalone
  script: | # Mehrzeiliger Shell-Skript
    echo "Running tests using Selenium Standalone Chrome service..."
    # Installiere nur curl und die notwendigen Tools für manuelle Downloads/Entpacken.
    apk update && apk add --no-cache curl wget unzip
    
    # --- AspectJ Weaver manuell herunterladen und platzieren (für javaagent) ---
    ASPECTJ_VERSION="1.9.20.1" 
    ASPECTJ_DOWNLOAD_URL="https://repo.maven.apache.org/maven2/org/aspectj/aspectjweaver/${ASPECTJ_VERSION}/aspectjweaver-${ASPECTJ_VERSION}.jar"
    
    echo "Downloading AspectJ Weaver version ${ASPECTJ_VERSION} from: ${ASPECTJ_DOWNLOAD_URL}"
    mkdir -p /opt/aspectjweaver # Ordner erstellen, wo das JAR liegen soll
    wget "${ASPECTJ_DOWNLOAD_URL}" -O /opt/aspectjweaver/aspectjweaver-${ASPECTJ_VERSION}.jar # Herunterladen an den festen Ort
    chmod +x /opt/aspectjweaver/aspectjweaver-${ASPECTJ_VERSION}.jar # Ausführbar machen (wichtig für javaagent)
    # --- ENDE AspectJ Weaver Setup ---

    # Warte, bis der Selenium Grid Service gestartet und bereit ist, Anfragen zu akzeptieren.
    echo "Waiting for Selenium Grid to be ready..."
    # Löse den GitLab Service-Alias in seine tatsächliche IP-Adresse auf (kann IPv4 oder IPv6 sein).
    SERVICE_IP=$(getent hosts ${SELENIUM_HOST} | awk '{ print $1 ; exit }')
    
    if [ -z "$SERVICE_IP" ]; then
      echo "Error: Could not resolve IP for Selenium service ${SELENIUM_HOST}. Aborting."
      exit 1
    fi
    
    # Exportiere die aufgelöste IP-Adresse als Umgebungsvariable, die der Java-Code nutzt.
    export SELENIUM_REMOTE_IP="${SERVICE_IP}"
    echo "Resolved Selenium IP: ${SELENIUM_REMOTE_IP}"

    # Führe einen Health Check durch, um zu warten, bis der Grid wirklich ready ist.
    SELENIUM_REMOTE_URL_FOR_CHECK="http://${SELENIUM_REMOTE_IP}:${SELENIUM_PORT}/wd/hub/status"
    if [[ "${SELENIUM_REMOTE_IP}" == *:* ]]; then
      SELENIUM_REMOTE_URL_FOR_CHECK="http://[${SELENIUM_REMOTE_IP}]:${SELENIUM_PORT}/wd/hub/status"
    fi

    echo "Waiting for Selenium Grid at ${SELENIUM_REMOTE_URL_FOR_CHECK} to be ready (curl check)..."
    while ! curl -sSL "${SELENIUM_REMOTE_URL_FOR_CHECK}" 2>&1 | grep -q "\"ready\": true"; do
      echo "Selenium Grid is not yet ready. Waiting..."
      sleep 1
    done
    echo "Selenium Grid is ready!"

    # Führe Tests mit Maven aus. Allure-Ergebnisse werden ins Standard 'target/allure-results' geschrieben.
    # Der Java-Code in TestSetup.java wurde angepasst, um SELENIUM_REMOTE_IP und SELENIUM_PORT zu verwenden.
    # Der javaagent-Pfad ist nun im pom.xml korrekt auf /opt/aspectjweaver festgelegt.
    mvn $MAVEN_CLI_OPTS test -Dsurefire.useFile=false -Dallure.results.directory=${CI_PROJECT_DIR}/target/allure-results # <-- HIER ABSOLUTER PFAD ZU target/allure-results
  artifacts:
    paths:
      - target/allure-results # Der Allure-Ergebnisordner, der an den nächsten Job übergeben wird.
    expire_in: 1 day

generate_allure_report_job:
  stage: report # Gehört zur 'report'-Phase
  image: maven:3.9.6-eclipse-temurin-21-alpine # Verwende das gleiche Basis-Image wie für den Test-Job
  needs:
    - job: test_job # Braucht den Test-Job
      artifacts: true # Fordert die Artefakte des Test-Jobs an (dies ist jetzt 'target/allure-results')
  script: |
    echo "Generating Allure report..."
    # Installiere curl, unzip und wget für die Allure CLI Installation
    apk update && apk add --no-cache curl unzip wget
    
    ALLURE_VERSION="2.27.0" 
    ALLURE_DOWNLOAD_URL="https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.zip"
    
    echo "Downloading Allure CLI version ${ALLURE_VERSION} from: ${ALLURE_DOWNLOAD_URL}"
    wget "${ALLURE_DOWNLOAD_URL}" -O /tmp/allure-commandline.zip
    
    unzip /tmp/allure-commandline.zip -d /opt/allure-framework
    chmod +x /opt/allure-framework/allure-*/bin/allure # Mach das Allure Binary ausführbar
    export PATH="/opt/allure-framework/allure-${ALLURE_VERSION}/bin:$PATH" # Füge Allure zum PATH hinzu

    # --- HINZUGEFÜGTER DIAGNOSE-SCHRITT ---
    echo "Listing contents of ${CI_PROJECT_DIR}/target/allure-results (should contain test results):"
    ls -la ${CI_PROJECT_DIR}/target/allure-results/ || echo "${CI_PROJECT_DIR}/target/allure-results directory not found or empty."
    # --- ENDE DIAGNOSE-SCHRITT ---

    # Generiere den HTML-Report. allure generate liest jetzt direkt aus dem Standard-Pfad, wo Artefakte entpackt werden.
    allure generate --clean ${CI_PROJECT_DIR}/target/allure-results -o target/allure-report
  artifacts:
    paths:
      - target/allure-report # Speichert den generierten HTML-Report
    expire_in: 1 week

pages:
  stage: deploy_report
  needs: ["generate_allure_report_job"]
  script:
    - echo "Deploying Allure report to GitLab Pages..."
    - mv target/allure-report/ public
  artifacts:
    paths:
      - public
  only:
    - master
    - main